# ==============================
# = Application Configurations
# ==============================
server:
  port: 8888

spring:
  application:
    name: easylearn

  # ==============================
  # = Spring Security
  # ==============================
  #  security:
  #    user:
  #      name: admin
  #      password: admin

  # ==============================
  # = Postgres DB Configurations
  # ==============================
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/easylearn
    username: postgres
    password: root
    initialization-mode: always
  jpa:
    generate-ddl: false
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation=true:show-sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
